# capsule version
version = "0.9.0"
deployment = "deployment.toml"

[rust]
workspace_dir = "."
docker_image = "thewawar/ckb-capsule:2022-08-01"

[[contracts]]
name = "covalent-type-script"
template_type = "Rust"

[[contracts]]
name = "covalent-lock-script"
template_type = "Rust"
