[[cells]]
name = "covalent-type-script"
enable_type_id = true
location = { file = "build/release/covalent-type-script" }

[[cells]]
name = "covalent-lock-script"
enable_type_id = true
location = { file = "build/release/covalent-lock-script" }

# # Dep group cells
# [[dep_groups]]
# name = "my_dep_group"
# cells = [
#   "my_cell",
#   "genesis_cell"
# ]

# # Replace with your own lock if you want to unlock deployed cells.
# # For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0"
hash_type = "type"

